// Generates one Next.js route file per entry in src/lib/site-pages.ts.
//
// Every generated file is a thin wrapper around <RenderPage/>, so page content
// and structure live in the manifest, not in 50-odd hand-maintained files.
// Re-run after editing the manifest.
//
// Usage: node scripts/generate-pages.mjs
import { mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const manifest = await readFile('src/lib/site-pages.ts', 'utf8');

// Pull slugs + titles from both the object literals and the pending() helper.
const slugs = [];
for (const m of manifest.matchAll(/slug:\s*"([^"]+)",\s*\n\s*title:\s*"([^"]+)"/g)) {
  slugs.push({ slug: m[1], title: m[2] });
}
for (const m of manifest.matchAll(/pending\(\s*"([^"]+)",\s*"([^"]+)"/g)) {
  slugs.push({ slug: m[1], title: m[2] });
}

if (!slugs.length) {
  console.error('No pages found in manifest — aborting.');
  process.exit(1);
}

const escape = (s) => s.replace(/"/g, '\\"');
let written = 0;

for (const { slug, title } of slugs) {
  const dir = join('src', 'app', ...slug.split('/'));
  await mkdir(dir, { recursive: true });
  const file = join(dir, 'page.tsx');
  const body = `import type { Metadata } from "next";

import { RenderPage } from "@/components/page/RenderPage";

// Generated by scripts/generate-pages.mjs — edit src/lib/site-pages.ts instead.

export const metadata: Metadata = {
  title: "${escape(title)} | Muktir Siksha College Of Education & Pharmacy",
};

export default function Page() {
  return <RenderPage slug="${escape(slug)}" />;
}
`;
  await writeFile(file, body, 'utf8');
  written++;
}

// Drop any previously generated route that is no longer in the manifest.
const keep = new Set(slugs.map((s) => s.slug));
const { readdir, stat } = await import('node:fs/promises');
async function prune(base, prefix = '') {
  let entries;
  try {
    entries = await readdir(base, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const rel = prefix ? `${prefix}/${e.name}` : e.name;
    const pagePath = join(base, e.name, 'page.tsx');
    let isGenerated = false;
    try {
      isGenerated = (await readFile(pagePath, 'utf8')).includes(
        'Generated by scripts/generate-pages.mjs',
      );
    } catch {}
    if (isGenerated && !keep.has(rel)) {
      await rm(join(base, e.name), { recursive: true, force: true });
      console.log('  pruned', rel);
    }
    await prune(join(base, e.name), rel);
  }
}
await prune(join('src', 'app'));

console.log(`\n${written} route files generated`);
console.log(slugs.map((s) => '  /' + s.slug).sort().join('\n'));
