import type { Metadata } from "next";

import { RenderPage } from "@/components/page/RenderPage";

// Generated by scripts/generate-pages.mjs — edit src/lib/site-pages.ts instead.

export const metadata: Metadata = {
  title: "Rules & Regulations | Muktir Siksha College Of Education & Pharmacy",
};

export default function Page() {
  return <RenderPage slug="rules-regulations" />;
}
